In [ ]:
import numpy as np
import pandas as pd
from sklearn import svm
import sklearn
import spacy
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from google.colab import files
import io

## Loading the dataset

In [ ]:
uploaded = files.upload()
df = pd.read_csv("SMSSpamCollection.txt",delimiter="\t",header=None,names=["S/H","text"])
df.head()

Saving SMSSpamCollection.txt to SMSSpamCollection (1).txt


S/H                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

## Extract the texts

In [ ]:
texts = [sentence for sentence  in df.loc[:, 'text']]
print(len(texts))
texts[:2]

5572


['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
 'Ok lar... Joking wif u oni...']

## Part-of-speech tagging of the first message

In [ ]:
nlp = spacy.load("en_core_web_sm")
doc = nlp(texts[0])
for token in doc:
    print(token.text,"--->", token.lemma_,"--->", token.pos_,"--->", token.is_stop)

Go ---> go ---> VERB ---> True
until ---> until ---> ADP ---> True
jurong ---> jurong ---> PROPN ---> False
point ---> point ---> NOUN ---> False
, ---> , ---> PUNCT ---> False
crazy ---> crazy ---> ADJ ---> False
.. ---> .. ---> PUNCT ---> False
Available ---> available ---> ADJ ---> False
only ---> only ---> ADV ---> True
in ---> in ---> ADP ---> True
bugis ---> bugis ---> PROPN ---> False
n ---> n ---> PROPN ---> False
great ---> great ---> PROPN ---> False
world ---> world ---> PROPN ---> False
la ---> la ---> PROPN ---> False
e ---> e ---> PROPN ---> False
buffet ---> buffet ---> NOUN ---> False
... ---> ... ---> PUNCT ---> False
Cine ---> Cine ---> PROPN ---> False
there ---> there ---> PRON ---> True
got ---> get ---> VERB ---> False
amore ---> amore ---> ADJ ---> False
wat ---> wat ---> PROPN ---> False
... ---> ... ---> PUNCT ---> False


## Lemmatizing and Removing stop words

In [ ]:
all_stopwords = nlp.Defaults.stop_words
texts_lemm_withoutSW = []
for sentence  in texts:
    doc = nlp(sentence)
    texts_lemm_withoutSW.append(" ".join([token for token in  [token.lemma_ for token in doc] if not token in all_stopwords]))
    
texts_lemm_withoutSW[:2]

['jurong point , crazy .. available bugis n great world la e buffet ... Cine amore wat ...',
 'ok lar ... joking wif u oni ...']

## Extract the classes

In [ ]:
targets = [kind for kind in df.loc[:, 'S/H']]
targets[10:20]

['ham', 'spam', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam']

In [ ]:
set(targets)

{'ham', 'spam'}

In [ ]:
targets = np.array([0 if target == 'ham' else 1 for target in targets])
targets[10:20]

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 1])

## Produce training and test data

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(texts_lemm_withoutSW,targets, test_size=0.1, shuffle=True) 

## X_train to a matrix of TF-IDF features

In [ ]:
count_vectorizer = TfidfVectorizer()
vocab = count_vectorizer.fit(X_train)
inputs = vocab.transform(X_train)
pd.DataFrame(inputs.toarray(), columns=count_vectorizer.get_feature_names())

00  000  000pe  008704050406  0089  ...  zoom  zouk  zyada   ú1  〨ud
0     0.0  0.0    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0
1     0.0  0.0    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0
2     0.0  0.0    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0
3     0.0  0.0    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0
4     0.0  0.0    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0
...   ...  ...    ...           ...   ...  ...   ...   ...    ...  ...  ...
5009  0.0  0.0    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0
5010  0.0  0.0    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0
5011  0.0  0.0    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0
5012  0.0  0.0    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0
5013  0.0  0.0    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0

[5014 rows x 7201 columns]

## SVM model

In [ ]:
svc = svm.LinearSVC()
svc.fit(inputs,y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

## X_test to a matrix of TF-IDF features

In [ ]:
X_test = vocab.transform(X_test)
pd.DataFrame(X_test.toarray(), columns=count_vectorizer.get_feature_names())

00       000  000pe  008704050406  0089  ...  zoom  zouk  zyada   ú1  〨ud
0    0.0  0.000000    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0
1    0.0  0.000000    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0
2    0.0  0.000000    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0
3    0.0  0.000000    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0
4    0.0  0.218023    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0
..   ...       ...    ...           ...   ...  ...   ...   ...    ...  ...  ...
553  0.0  0.000000    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0
554  0.0  0.000000    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0
555  0.0  0.000000    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0
556  0.0  0.000000    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0
557  0.0  0.000000    0.0           0.0   0.0  ...   0.0   0.0    0.0  0.0  0.0

[558 rows x 7201 columns]

In [ ]:
svc.score(X_test, y_test)

0.9874551971326165

In [ ]:
svc.predict(X_test[:20]), y_test[:20]

(array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]))

### Confusion matrix

In [ ]:
confusion_matrix = sklearn.metrics.confusion_matrix(y_test, svc.predict(X_test))
confusion_matrix

array([[482,   1],
       [  6,  69]])

## Naive Bayes

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(inputs.toarray(), y_train).predict(X_test.toarray())
print("Number of mislabeled points out of a total %d points : %d"% (X_test.shape[0], (y_test != y_pred).sum()))

Number of mislabeled points out of a total 558 points : 84


## Random Forest

In [ ]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor

# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)

# Train the model on training data
rf.fit(inputs, y_train);

In [ ]:
# Use the forest's predict method on the test data
predictions = rf.predict(X_test)

# Calculate the absolute errors
errors = abs(predictions - y_test)

# Print out the mean absolute error
print('Mean Absolute Error:', round(np.mean(errors), 4), 'degrees.')

Mean Absolute Error: 0.0335 degrees.
